TRUNCATE Customers;
TRUNCATE Passwords;
TRUNCATE OverdraftLogs;
TRUNCATE TransactionHistory;
TRUNCATE TransferHistory;
TRUNCATE CryptoHistory;
TRUNCATE CryptoHoldings;
TRUNCATE SP500History;
TRUNCATE SP500Holdings;